### ISSUE TITLE
Death mentor not implemented

### ISSUE THREAD

**Issue by chummer5hasanerror** [chummer5a/chummer5a#1743]
### Environment
Chummer Version: .109

### Expected behaviour
After selecting Death Mentor as a positive quality, a dialog will pop-up where the player selects the mentor spirit advantage from a list of available knowledges.  
The selected knowledge skill will populate in the characters knowledge skill area at +4 ranks
The ranks can be increase to 6 via bonus knowledge points.
All of the available knowledge skills potentially provided by the death mentor advantage can be selected from the knowledge skill dropdown menu and have an auto-populating category (as is normal for knowledge skills)

**Comment by chummer5hasanerror** [comment]
Currently Nightly .130 
is almost fully implemented, however the knowledge skills are being added as a misc modifier, when RAW states this should be 'Ranks,' the distinction being:
knowledge rating 1 + (4 misc bonus as implemented currently) = rank 2, will costs 2 karma to increase to rank 2
knowledge rating 1 + (4 ranks, as is RAW for Death Mentor in FA) = rank 5, will cost 5 karma to raise to rank 6

**Comment by DelnarErsike** [comment]
Could you please check to see if it is fully fixed in the latest Nightly build?

**Comment by chummer5hasanerror** [comment]
Verifying problem is still existent in the same from (adding ranks that do not increase karma cost) in current nightly (195.22)

To reiterate the specifics, the usage of the word 'ranks' directly implies that this is bonus ranks, not just bonus dice.  Bonus dice have no effect on karmic cost for skills, but Ranks do; Ranks increase the amount of kamra required to raise the skill.
