### ISSUE TITLE
Extra point error when going career mode

### ISSUE THREAD

**Issue by drakir75** [chummer5a/chummer5a#1769]
### Environment
Chummer Version: 5.193.136
Environment: Windows 10
Runtime: probably .NET 4.5.1

### Expected behaviour
No error message if character correctly built when saving to career mode.

### Actual behaviour
An "Extra points" message saying I have all my attribute points and another saying all my special points left to spend when they are spent.

### Steps to reproduce the behaviour
Create any character. Save in career mode.

**Comment by chummer5a** [comment]
I believe this is fixed in current commits?

**Comment by drakir75** [comment]
Seems to be back/still here in 5.194.0

**Comment by drakir75** [comment]
I still get the same extra points left message in version 5.195.8.

**Comment by chummer5a** [comment]
Nightly builds only run daily now, makes it easier for me to make commits without spamming a million builds. The next build is scheduled for a little under an hour from now.
