### ISSUE TITLE
Spell categories not printed correctly

### ISSUE THREAD

**Issue by holgerschlegel** [chummer5a/chummer5a#1790]
### Environment
Chummer Version: 5.193.146
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Print the correct translated spell categories.

### Actual behaviour
The spell category of all spells is printed (in the line above the spells) as "Unknown" (translated to the set language, so "Unbekannt" in my case).

Reason:
The xml files saved from the print dialog already contains translated values for spell/category.
The sheets file xt.spells.xlst contains a choose block (starting at line 55) to translate the category string from fixed values like 'Combat' into the string from the sheet localization.

So either Chummer5 must generate the xml content with that english standard values.
Or the xslt file must be changed to simply output what is found in the category xml tag. This variant would also lead to a spell category sorting based on the chosen language.

But there might be other aspects to decide which is the correct/better solution to solve this.

### Steps to reproduce the behaviour
Set Chummer5a to a language other than English.
Create/open a character with a spell.
Open the printout.

**Comment by Lochabar** [comment]
I've already spotted this problem. I will provide a fix, with other character sheets changes, in the near future.

**Comment by holgerschlegel** [comment]
If you are interested, here is a small list of changes that I apply locally before using the current sheets.

* Remove the "text-transform: uppercase;" transformation from the CSS formats. At least in German titles/headers/labels are usually written in normal mixed case. And for me, an all upper case word is harder to read.
* Added a small for-each loop over the "clips/clip" of the ranges weapons to show the not empty clips with the loaded rounds (type and number). Otherwise ammunition loaded in the clips is not printed at all - not in the equipments list and not in the weapons list.
One row for each clip. Added directly below the block for weapon accessories.

**Comment by Lochabar** [comment]
I don't think I changed the way ammunition and spare clips are shown in the gear list, but the testing version of my character sheets show both:

![ammunition](https://user-images.githubusercontent.com/17562417/28047237-47d3b15e-65ae-11e7-8993-c57f00532874.png)

**Comment by Lochabar** [comment]
I switched to German and the ammunition and clips are shown:

![ammunition de](https://user-images.githubusercontent.com/17562417/28047338-0347af6c-65af-11e7-9f6c-b0056a718b93.png)

**Comment by holgerschlegel** [comment]
So far I always added spare clips as accessories to the weapon. Not as a separate equipment.
If added as weapon accessories, the spare clip is not printed in the equipments list at all. Thus the loaded ammunition is not shown.
I simply did not noticed that a space clip can be added as a separate equipment too. Thanks for the hint :)

**Comment by chummer5a** [comment]
I think this is fixed in current builds, yes?

**Comment by holgerschlegel** [comment]
No, not fixed. In version 5.193.169 the spell categories are all printed as "Unbekannt", which means "Unknown".

**Comment by Lochabar** [comment]
I have been waiting for #1795 to be fixed so that I can check the French versions of the character sheets.

I will provide the character sheet changes shortly.

**Comment by Lochabar** [comment]
Changes provided in issue #1810 .

**Comment by holgerschlegel** [comment]
Now fixed with version 5.193.180.
