### ISSUE TITLE
Cat totem

### ISSUE THREAD

**Issue by GigglingAmbush** [chummer5a/chummer5a#1844]
### Environment
Chummer Version: 5.193.190
Environment: Win 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Cat totem adds 2 levels of light body. 
Being able to add more levels of light body.
To not crash when removing "mentor spirit (cat)" quality.

### Actual behaviour
Cat totem adds 1 level of light body.
Not able to add more levels.
Crashes when removing "mentor spirit (cat)" quality..

### Steps to reproduce the behaviour
Add "mentor spirit (cat)" quality.
The crash only happens after i have viewed the adept power tab after loading the character
### Link to affected character file

[Troll bow cat adept 800.zip](https://github.com/chummer5a/chummer5a/files/1185893/Troll.bow.cat.adept.800.zip)

**Comment by chummer5a** [comment]
There's something janky with the file, it's got the improvements for mentor spirit listed twice and you're over the quality cap. I removed the mentor spirit and ambidextrous qualities and re-added the mentor spirit and everything seems fine now. 

[Troll bow cat adept 800.zip](https://github.com/chummer5a/chummer5a/files/1187619/Troll.bow.cat.adept.800.zip)

**Comment by GigglingAmbush** [comment]
I can replicate it with a completely new character too. 
[Empty replicated.zip](https://github.com/chummer5a/chummer5a/files/1188244/Empty.replicated.zip)

**Comment by chummer5a** [comment]
Hmmm. Seems to be a stack overflow due to the maximum levels being higher than your current magic, so when you increase the magic rating it tries to increase it again. That's how I was able to get it to crash, at least. Shouldn't be super difficult to resolve. Sorry for the long delay in response.

**Comment by chummer5a** [comment]
I believe this is fixed in current builds. Could you please test and confirm?

**Comment by GigglingAmbush** [comment]
Sorry, been away for a while. Tried to confirm but I'm still getting the
error on that character, and a completely new troll with adept and cat
mentor.
I used last stable release, should i try the last nightly?

4. nov. 2017 15:46 skrev "Chummer 5 Is Alive" <notifications@github.com>:
