### ISSUE TITLE
Alter Memory

### ISSUE THREAD

**Issue by HarleeKnight** [chummer5a/chummer5a#2148]
(Please fill out the below as accurately as possible. More detail makes it easier for us to find the problems and fix them.)

### Environment
Chummer Version: (What version of chummer are you running?
Environment: Windows 10
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Wanted to make Alter Memory a limited spell
### Actual behaviour
Program Crash as soon as you click "limited" when Alter Memory is highlighted
### Steps to reproduce the behaviour
tried 3 times with same results

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
What version are you on? I believe this is fixed in current nightlies.

**Comment by HarleeKnight** [comment]
Version 5.195.0

**Comment by HarleeKnight** [comment]
Just updated to latest version (Build 195) and restarted and problem still exists.

**Comment by chummer5a** [comment]
Release build hasn't been updated in a few months, use the latest nightly. https://github.com/chummer5a/chummer5a/releases/tag/Nightly-v5.195.100
