### ISSUE TITLE
The localized text doesn't fit the labels in frmCreate.

### ISSUE THREAD

**Issue by luizbgomide** [chummer5a/chummer5a#2374]
The pt-br text doesn't fit the labels in frmCreate.
The following have problems:
Karma Summary -> Knowledge Skills (Perícias de Conhecimento)
Other Info -> Initiatives (Iniciativa da Matriz, de Fusoconexão)
Spell Defense -> Countermagic Dice (Dados de Contramágica)
Skills -> Knowledge skills section: all the labels in the top of this section.
Relationships -> Contacts: Prefered Payment (Pagamento Preferido), Hobbies/Vices (Hobbies/Vices).

I can "fix" those by offseting ou slighting moving them in the form, can I do that? I would have to increase the frmCreate width by a few pixels for that to work nicelly.

**Comment by luizbgomide** [comment]
I'm working on that, I already fix some of the problems.

**Comment by holgerschlegel** [comment]
I noticed the same problem with not fully visible texts when using German as language.

It would be nice to have a somehow dynamic layout for widgets that contain text (mainly labels and buttons).
Know sure whats possible in DotNet and/or C#. I just known that other UI toolkits (my primary language is Java) provide dynamic layout managers that automatically size labels and buttons based on the set texts.

**Comment by luizbgomide** [comment]
I'm working on fixing those as I find. Post the ones you found here as for sure they affect Portuguese as well. I will try to fix those too.

**Comment by holgerschlegel** [comment]
Here are some places I found by a quick look using German as UI language:
- Character Roaster labels on the details pane beside the tree. The last label (configuration/settings file) is to short. With the German text "Konfigurationsdatei", the last character is missing.
- On the skills tab, the 'column' for the skill group ratings is to small to show the translated text for broken groups (which is "Gebrochen").
- On the skills tab, the 'column' for the skill names is to short for one German skill name. The translation "Elektronische Kriegsführung" (Electronic Warfare) does not fit completely.
- On the tab for spell defense dice pools, the label 'column' is to small. The German text "Direktes Widerstehen - Körperlich" (in the 4th row) is missing half of the last character.
- On the Karma and Nuyen tab, the checkbox for showing free entries overlaps the 3rd button due to longer texts on the buttons.
- On the Improvements tab, the button to add a group overlaps the delete button.

**Comment by luizbgomide** [comment]
I made a pull request where I fixed a few of those, when it is accepted it would appear the next nightly.
I'm waiting @DelnarErsike or @chummer5a to accept them 😁 
I couldnt find some of the ones you mentioned, if you can take a screenshot showing the problematic ones it would help.

**Comment by holgerschlegel** [comment]
Here is a zip file with screen shots for the overlappings that do still exist in version 5.197.12.
Thanks for your work to solve those issues.

[Chummer5a-5.197.12-OverlappingWidgets.zip](https://github.com/chummer5a/chummer5a/files/1662866/Chummer5a-5.197.12-OverlappingWidgets.zip)
