### ISSUE TITLE
Knowledge skill specializations bugged

### ISSUE THREAD

**Issue by MaraFaye** [chummer5a/chummer5a#2522]
### Environment
Chummer Version: 5.198.12
Environment: Windows 7
Runtime: 4.7.1

### Expected behaviour
Adding a specialization for a knowledge skill during creation deducts the cost and adds the chosen specialization.

### Actual behaviour
All knowledge skill flash shortly and that was it, nothing added, nothing deducted.
Also when manually entering a specialization, the cursor always jumps to the first position after typing, messing manual addition of skills up too.

### Steps to reproduce the behaviour
Create a new character and try to add a specialization for a knowledge skill.

**Comment by MaraFaye** [comment]
Addition:
Apparently this only happens to characters of which ones creation started in a previous version (5.198.9 in this case) and are then loaded in version 5.198.11. Characters created in the latest version do not suffer from this (At least until they are put into career mode, then they are affected from the bug decribed below).

Characters put into career mode and adding specializations suffer from a similar effect, the karma is deducted and it appears normal in the expenses listing, but the specialization is not added on the actual skill screen.

**Comment by chummer5a** [comment]
That's interesting. Um. If you remove the skill and retry it, does it still happen? Can you provide me with a sample character?

**Comment by MaraFaye** [comment]
[Test.zip](https://github.com/chummer5a/chummer5a/files/1754369/Test.zip)

I tried to replicate the error with version 5.198.14, but apparently whatever caused the issue in itself doesn't exist anymore.
The only thing that remains is that, during career mode, the specializations for skills, (action or knowledge) don't show up until the char was saved and loaded again.
Aside from that it seems to work normally now.

**Comment by MaraFaye** [comment]
Update: re-encountered the bug.
[Test2.zip](https://github.com/chummer5a/chummer5a/files/1754542/Test2.zip)

Adding specializations to knowledge skills on this char fails so far.

**Comment by DelnarErsike** [comment]
The bug has been fixed in the dev branch, but it will not be pushed into a new nightly until a new nightly releases.

The source of the bug was that Chummer5a fires off an "update information related to what specializations to display" event whenever the list of a skill's specializations is updated or a specialization therein is changed. However, the event itself was set up incorrectly: it said to update information related to `DisplaySpecializationMethod` (which is a function that fetches specializations to display in a specified language), but it should have said to update information related to `DisplaySpecialization` (which is a property that calls DisplaySpecializationMethod with the current UI language of Chummer5a). The text you see in the UI that display specializations in career mode is bound to `DisplaySpecialization`, not to `DisplaySpecializationMethod`, so it never got the signal to update itself. Check code changed in commit 6d6c40b2fb060ba30b71d6aef2601aa573eeb53a if you're curious about the details.

**Comment by MaraFaye** [comment]
Have to report that it still exist in part, I didn't do an exhaustive test now, but with the language skills Or'zet and Sperethiel chummer keeps adding the "Dialect" specialization when loaded on a character in create mode.
