### ISSUE TITLE
Proteus Poseiden RCC

### ISSUE THREAD

**Issue by MaraFaye** [chummer5a/chummer5a#2583]
### Environment
Chummer Version: 5.198.27
Environment: Windows 7
Runtime: (If you don't know this, it is probably .NET 4.5.1)

### Expected behaviour
Data Proc: 6 / Firewall 5

### Actual behaviour
Data Proc 5 / Firewall 6
Stats are like the Vulcan Liegelord, which would make the Poseidon redundant if it had the same stats.
Other stats are correct.

### Steps to reproduce the behaviour
Look at it in the RCC section.

### Link to affected character file
(Enter text here)

**Comment by chummer5a** [comment]
RAW it's correct, hasn't been any errata on it.

**Comment by MaraFaye** [comment]
![rccs](https://user-images.githubusercontent.com/27777147/37254412-b3d06c22-253d-11e8-8465-07483c1d778c.PNG)

German BRB second printing (is errata'd).

**Comment by nickschurch** [comment]
This isn't fixed in the latest stable build (5.225.0.0) so not sure why it's marked closed.

![image](https://github.com/chummer5a/chummer5a/assets/2212398/f9fd27b3-9ac5-4c28-9a30-238000af8fd9)

**Comment by ArchonMegalon** [comment]
Maybe, because it is fixed in the nightly builds. They will become the next
stable ones. Can you check?

Because from a development perspective, it IS fixed in that case - it is
just not released yet.

**Comment by nickschurch** [comment]
The issue is still present in 5.225.329.0

**Comment by JoschiZ** [comment]
```xml
<!-- German Data Changes/amend_gear.xml -->
    <gear> <!-- Proteus Poseidon -->
      <id>f9941dbe-1db1-4948-a8be-d760733446ea</id>
      <dataprocessing>6</dataprocessing>
      <firewall>5</firewall>
    </gear>
```
You sure that this issue still persist? Because the German Data Changes cutomdata should correct this.
Remember that this is a change in an German book. That means you have to activate the German Data Changes customdata.

**Comment by nickschurch** [comment]
Ahhh, OK, that was the bit I missed. That's it working now (although it doesn't update existing kit, you need to add the RCC again to get the new values). Will the german updates become core in the release, or do they need to be enabled in the stable version too?

**Comment by JoschiZ** [comment]
It will not become core.

Chummer core only implements the English version of the rules and errata to those.
Everything else is opt in using the customdata system.

That allows you to modify things for yourself as you see fit.

A list of those are distributed with Chummer directly. The German Data Changes being a notable one which implements all the changes that Pegasus did.
