### ISSUE TITLE
Chummer won't start, produces TypeLoadException

### ISSUE THREAD

**Issue by nihilazo** [chummer5a/chummer5a#2584]
### Environment
Chummer Version: 5.198
Environment: Arch linux
Runtime: Mono 5.4.1

### Expected behaviour
The Chummer program starting.

### Actual behaviour
An error on the command line:
```
Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 01000253 (from typeref, class/assembly System.Runtime.ProfileOptimization, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 01000253 (from typeref, class/assembly System.Runtime.ProfileOptimization, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)

```

### Steps to reproduce the behaviour
Run chummer under this environment

**Comment by lukeoftheaura** [comment]
@DelnarErsike just closing the issue without comment?

**Comment by OLStefan** [comment]
The issue was closed via a commit which should fix this issue. Indicated by the string of letters and numbers in the closing message.

**Comment by Lightsockie** [comment]
Problem still seems to exist. Using latest nightly (built from that commit, Nightly-v5.198.30) I get the error described in the OP. Same environment as OP, too

**Comment by Lightsockie** [comment]
Yep. The package in Arch's repo was built back in November. I'll see about pulling this nightly mono build from AUR and get back to you if that fixes it

**Comment by Lightsockie** [comment]
With the nightly build of mono the exception still gets thrown.

`Mono JIT compiler version 5.9.0.375 (master/c58ab6f Mon Mar 12 03:36:26 AKDT 2018)`
```
Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 01000256 (from typeref, class/assembly System.Runtime.ProfileOptimization, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 01000256 (from typeref, class/assembly System.Runtime.ProfileOptimization, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
```

**Comment by chummer5a** [comment]
Closing as stale; unable to replicate using https://github.com/chummer5a/chummer5a/wiki#using-wine
