### ISSUE TITLE
Mentor spirit/adept power glitch

### ISSUE THREAD

**Issue by Verecoth** [chummer5a/chummer5a#335]
So, I was trying to make an adept character and there seems to be something wrong with adept powers. When I add them they show up as rating 0 and can't be increased. In the case of a power added via Mentor Spirit this actually gave me an extra 0.5 PP because the power cost was -0.5 PP.

Here's the chummer file: https://drive.google.com/file/d/0B7MDGEbiDFrkdTdGNnIyNHloNTA/view?usp=sharing

**Comment by joha4270** [comment]
Free adept powers being broken have been known as broken for quite a long time.

Just always been other stuff on the priority queue.

**Comment by joha4270** [comment]
Fixed in 173

**Comment by JonJanness76** [comment]
I have build:173 and I am still having this problem when doing a priority build but not if I am doing a karma build. It will also messes with the other Adept power by reducing all levels to 1 and I can not increase any powers. I did Download Verecoth's Chummer file and I was getting the same problem. Like Verecoth I had selected seducer as a mentor spirit. aslo

**Comment by joha4270** [comment]
I would need a .chum5 file to diagnose this.

**Comment by JonJanness76** [comment]
So I had some time to play with chummer a bit more today and it looks like its just when adding the seducer mentor spirit is when it messes up the other adept powers.
Thanks
https://onedrive.live.com/redir?resid=6D44735F46801D7D%21105
