### ISSUE TITLE
Metamagic - Tradition

### ISSUE THREAD

**Issue by SaMoriarty** [chummer5a/chummer5a#4385]
Hi,

**Chummer Version :** 
5.211.0

**Expected Behaviour :** 
To be able to pick the metamagic "Corruption" at the first level of initiation as imposed by the Tradition : "Disciple of the Old Gods". 

**Actual behaviour :**
1 : At first level of initiation : you have to choose the "paradygm's shift : toxic" as your first metamagic
2 : At second level of initiation : you can choose the Metamagic "corruption".

**Comment by chummer5a** [comment]
Without checking changelogs, I'm pretty sure this was resolved. Please update to a current version of Chummer, you're three major revisions behind. https://github.com/chummer5a/chummer5a/releases/latest

**Comment by SaMoriarty** [comment]
I've updated to the version 5.214.0. 

The problem isn't solved.

**Comment by DelnarErsike** [comment]
I believe this was fixed in #4387. Please re-open if it was not.
