### ISSUE TITLE
Auto-Generated Issue from Crash: ID d7b518d3-49d3-4d7c-a7a4-59fc113f3bed

### ISSUE THREAD

**Issue by Perrud** [chummer5a/chummer5a#4682]
### Environment
Crash ID: d7b518d3-49d3-4d7c-a7a4-59fc113f3bed
Chummer Version: 5.219.0
Environment: Windows 10 Pro
Runtime: 4.0.30319.42000
Option upload logs set: OnlyMetric
Installation ID: 6c769aaa-4ae4-4dae-889d-ce96d7965ff9

### Expected behaviour
Add a support for weapon in a vehicle

### Actual behaviour
crash

### Steps to reproduce the behaviour
add a car -

**Comment by DelnarErsike** [comment]
I believe this fixed in 5.220. Could you please double-check?

**Comment by PirateSwayze** [comment]
I am still having this issue after upgrading to 5.220.0

 Here is what I am doing:

Character in Create Mode
Add MCT-Nissan Roto-drone
Add Weapon Mount
Crash followup id = b6481a02-c637-4feb-97d1-0dff2011229b

**Comment by Perrud** [comment]
Sorry, I've seen the answer just now. But the problem persists in .22 ;)

**Comment by DelnarErsike** [comment]
The crash was fixed in a commit that will only be in 5.220.3 onwards.
