### ISSUE TITLE
Magical Traditions Health Spirits and Tradition Names

### ISSUE THREAD

**Issue by o8livion** [chummer5a/chummer5a#4854]
**Describe the bug**
the bug blanks out the healing aspect spirits of the traditions and the name of the tradition. sometimes even the drain attributes are missing. i can not reproduce that part regularly tho, might have something to do with crashes.

**To Reproduce**
1. take magician positive quality
2. go to "spells & spirits"
3. take or create a tradition with all necessary things filled
4. save character
5. restart chummer (sometimes the bug isn't reproduced when not closing chummer)
6. load character
7. go to "spells & spirits"
8. see error

**Expected behavior**
the health-spirit type is completely blank, not even a dropdown menue available. this occurs if character is saved in creation mode and even saved from creation to career mode.

**Screenshots**
![custom tradition before](https://user-images.githubusercontent.com/14218286/178311307-0a603731-43b0-45e3-8fcf-18e1ccc3e3c5.jpg)
![custom tradition after](https://user-images.githubusercontent.com/14218286/178311318-8eb8cbb4-8a8f-41e3-874c-5aba1ab6beb2.jpg)
![shamanic before](https://user-images.githubusercontent.com/14218286/178311325-d2f51a7a-0fd8-44fb-b29f-30190e9d6683.jpg)
![shamanic after](https://user-images.githubusercontent.com/14218286/178313750-df5a0d9c-d1e7-4ae8-81b0-8cbb7f5cdfb0.jpg)

and here without mentor spirits:
![shamanic before (no mentor)](https://user-images.githubusercontent.com/14218286/178311504-aeed18bc-bf12-436d-8c28-717a3f7109c9.jpg)
![shamanic after (no mentor)](https://user-images.githubusercontent.com/14218286/178311514-ddaa804c-f484-483f-9e23-33649864254d.jpg)

when reproducing for screenshots i had an additional unexpected experience which i include in additional screenshot. when selecting something out of that list, chummer crashes without error description.
![completely unexpected behaviour](https://user-images.githubusercontent.com/14218286/178311526-24cf3c14-7090-44f3-b4f4-27945c35c909.jpg)

**Character File**
Thi is one of the characters that is saved and has this issue when i try to open it. every mage i built has it. i think that problem occured even in the milestone version.
[Bella.zip](https://github.com/chummer5a/chummer5a/files/9085903/Bella.zip)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Version 5.222.156

**Additional context**
here is the file with the character settings
[o8livions standards.zip](https://github.com/chummer5a/chummer5a/files/9085894/o8livions.standards.zip)

**Comment by bulldogc** [comment]
I can confirm the same issue with the disappearing health. For me it seems to go away after i save and close, it gets returned if i change the tradition to a new choice.

**Comment by chummer5a** [comment]
Resolved in [earlier commits.](https://github.com/chummer5a/chummer5a/commit/5f55c328051cc61a19d84ccec658b03026044f25)

**Comment by o8livion** [comment]
ok, yes, the health category spirit is there.
but sorry to put it out again: the tradition name is still missing =)
