### ISSUE TITLE
Chummer keeps crashing

### ISSUE THREAD

**Issue by TheeOk1** [chummer5a/chummer5a#4912]
Hello, I'm new to github and this issue seems to be a personal issue but I can't seem to use a majority of Chummer's features without it crashing. This issue carries over to older versions and acts consistent in that I can use the Tools options, all except for checking for updates: the latter crashing when attempting a clean reinstall or updating from an older version. The documentation of a Crash report also seems to fail a majority of the time, when documenting at all it just leaves a blank text file., though I'm not sure if that matters at all. In the end I'm usually left with a crash report that cant be read as it goes beyond the viewable boundaries of my PC. Here's a screenshot of such a crash report as well as the the problem event specific to my PC: Problem Event Name: CLR20r3.

![Screenshot (19)](https://user-images.githubusercontent.com/113275961/189542110-9b5bea3b-42d5-48e3-9f07-d9acac390391.png)

**Comment by chummer5a** [comment]
That cast bug is resolved in the nightlies. Issue with natural weapons, I believe.

**Comment by TheeOk1** [comment]
Which version? I've tried every one to to .185 and am still having

**Comment by TheeOk1** [comment]
Which version? I've tried every one to to .185 and am still having the same issue.

**Comment by JoschiGrey** [comment]
Did you test it on the newest Nightly Version 5.222.215?
You can just allow chummer to update to nightlies in the option to always be on the newest version.

**Comment by TheeOk1** [comment]
Yes, I did. To double check I did a manual reinstall of .213 and .215, to reiterate, the updating issue is only a symptom of the problem. I can't use ANY features, most importantly creating a new character also crashes the application.

**Comment by chummer5a** [comment]
Can you provide a screenshot of the crash report you are getting after updating?

**Comment by DelnarErsike** [comment]
Closing this issue due to its age and the fact that it has likely been fixed since it has been posted (since there have been a lot of fixes for crashes that would occur randomly and/or in unexpected places).
