### ISSUE TITLE
Rigger 5.0 Weapon Mounts (Can't add a weapon)

### ISSUE THREAD

**Issue by GrazalThruka** [chummer5a/chummer5a#753]
### Expected behaviour

Attempting to place a weapon on any of the Rigger 5.0 weapon mounts

### Actual behaviour

Chummer5 displays the message "Weapons can only be added to weapon mounts"

### Steps to reproduce the behaviour
1. Purchase a Rigger 5.0 weapon mount (Any kind)
2. Right-click on the mount
3. Select Weapons -> Add Weapon

**Comment by chummer5a** [comment]
Should be fixed in the nightlies. 5.178 included them as basic modifications, but there wasn't any code support for it. Please try the latest release build from github.com/chummer5a/chummer5a/releases and see if that sorts you out.

**Comment by GrazalThruka** [comment]
I downloaded version 5.179.742 (The Latest I could find), but the issue still persists. Am I downloading the wrong version?

**Comment by chummer5a** [comment]
No, the nightlies are failing at the moment. I should have it fixed shortly.

**Comment by chummer5a** [comment]
There we go, please try Nightly-v5.179.758.

**Comment by fungasaurjr** [comment]
This issue still exists in 5.179.769.
