### ISSUE TITLE
Karma Cost for Edge Inconsistent

### ISSUE THREAD

**Issue by arcvalor** [chummer5a/chummer5a#858]
### Chummer Version 

0.5.178

### Expected behaviour

Edge costs [New Value] x 5 to raise(15 to raise from 2 to 3, 20 more to go from 3 to 4)

### Actual behaviour

Edge costs 70 to raise from 2 (base) via Karma to 3.  If Base raised to 3 with Special Attribute points, costs 90 to go from 3 to 4 with Karma.

### Steps to reproduce the behaviour

New Character, Priority, Prime Runner
Priority D Race: Human
Priority A Attributes
Priority C Special: Adept, Skill: Blade
Priority B Skills
Priority E Money

Raise Magic from 4 to 6 using Special Attribute Points
Raise Edge using Karma

**Comment by OLStefan** [comment]
Already fixed in newest stable Release. It is found [here](https://github.com/chummer5a/chummer5a/releases/latest)

**Comment by arcvalor** [comment]
Except I am USING version 0.5.178.  I downloaded it today.  This bug persists.  So please reopen this thread.  Thanks!

**Comment by joha4270** [comment]
Your original post said 175.

**Comment by OLStefan** [comment]
Already fixed in latest Nightly Release, found [here](https://github.com/chummer5a/chummer5a/releases/tag/Nightly-v5.179.902)

**Comment by arcvalor** [comment]
Great, thanks!
